### ISSUE TITLE
Use Parameters.jl to ease maintenance of parameter struct

### ISSUE THREAD

**Issue by jmpohl** [NREL/REopt_Lite_API#37]
* **I'm submitting a ...**
  - [x] feature request

I have been adding fields to the `Parameter` struct in *reo/src/utils.jl* and have found it cumbersome to have to reorder the arguments of the `Parameter` constructor every time I move things around in the struct definition. Turns out [Parameters.jl](https://github.com/mauro3/Parameters.jl) is made for just such a use case and comes with some nice additional functionality that might simplify upstream code. I'll give it a look when I have more free time

**Comment by NLaws** [comment]
@jmpohl Would Base.@kwdef address this issue? Then we don't have to add Parameters.jl to dependencies.

**Comment by NLaws** [comment]
This issue was addressed with https://github.com/NREL/REopt_Lite_API/pull/53 and https://github.com/NREL/REopt_Lite_API/pull/54
