### ISSUE TITLE
Cbc.jl provides optimal solution with constraint violations

### ISSUE THREAD

**Issue by NLaws** [NREL/REopt_Lite_API#46]
`reo.tests.test_blended_rate.TestBlendedRate.test_time_of_export_rate` is failing with the Cbc solver because it is allowing `dvRatedProd` to be negative, in effect exporting PV production without buying PV system. It does produce the same optimal LCC as with Xpress.jl. 

I tried taking:
```
dvRatedProd[p.Tech, p.Load, p.TimeStep, p.Seg, p.FuelBin] >= 0
```
out of the block variable declaration in reopt.jl and replacing it with:
```
@variable(REopt, dvRatedProd[p.Tech, p.Load, p.TimeStep, p.Seg, p.FuelBin], lower_bound=0)
```
which made dvRatedProd _less_ negative, and still the same optimal LCC.

This issue is occurring with REopt Lite v1.0.0 and:
```
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
```
in the Ubuntu 18.04 docker container. 

@jmpohl @sakshi-mishra @TK-23 shall we disable the Cbc tests for now? Other options?

**Comment by jmpohl** [comment]
I think we disable them for now, but keep this as high priority. I am pretty sure we want to do a publication on about different solvers with REopt OS so it will definitely need to get handled for that work.

**Comment by NLaws** [comment]
I have disabled the Cbc work flow [here](https://github.com/NREL/REopt_Lite_API/commit/a02591712f6969da6a5e7754b5166cdc1269757a). We should reinstate these tests after the reformulation is merged into develop.

**Comment by NLaws** [comment]
Closing this Issue since it is a problem with Cbc and not REopt
