### ISSUE TITLE
create cost curve inputs

### ISSUE THREAD

**Issue by NLaws** [NREL/REopt_Lite_API#75]
JuMP model does have piecewise linear cost curves, but they are currently are only used to account for incentive size limits

**Comment by Bill-Becker** [comment]
@NLaws I think we can close this because it is addressed in the current pull request for cost curve functionality (for now, just for CHP).

**Comment by NLaws** [comment]
@Bill-Becker should we leave it open for techs other than CHP?

**Comment by Bill-Becker** [comment]
@NLaws I'm fine leaving it open, but is this the place we put all features that we envision adding in the future? Or are there select features, like this one, that have been requested enough that we call them issues?

**Comment by NLaws** [comment]
@Bill-Becker good question. The nice thing about using issues is that it is public, so anyone can see what features have been requested, make feature requests, and comment on them. Pivotal obviously has its strengths - but is not public. Perhaps we can discuss at next REopt Lite meeting?
